fusion-e/nativeedge-plugins-sdk

- CHANGELOG.txt
- cloudify_common_sdk/exceptions.py
- cloudify_rest_sdk/tests/test_sdk.py
- cloudify_rest_sdk/utility.py
- cloudify_terminal_sdk/base_connection.py
- cloudify_terminal_sdk/netconf_connection.py
- cloudify_terminal_sdk/terminal_connection.py
- cloudify_terminal_sdk/tests/fake_server.py
- cloudify_terminal_sdk/tests/test_base_connection.py
- cloudify_terminal_sdk/tests/test_netconf_connection.py
- cloudify_terminal_sdk/tests/test_terminal_connection.py
- setup.py
- test-requirements.txt
* Reorganize connection code for reuse netconf/terminal ssh connection
* Use common exception for all code parts
* Add netconf fake server for check clients
> CYBL-654: Reorganize connection code

- CHANGELOG.txt
- README.md
- cloudify_rest_sdk/tests/test_sdk.py
- cloudify_rest_sdk/utility.py
- cloudify_terminal_sdk/tests/fake_server.py
- setup.py
- Autocheck content type by headers
- Save headers to response by filtering
- Use headers in request
- Add urlencoded parameters support
- Merge params with urlencoded payloads
- Show connect information on netconf server start
> Rest headers

- CHANGELOG.txt
- cloudify_common_sdk/resource_downloader.py
- setup.py
Added a check in case of git import error
> Handle Resource Downloader missing Git installation

- CHANGELOG.txt
- cloudify_common_sdk/resource_downloader.py
- cloudify_common_sdk/tests/test_resource_downloader.py
- setup.py
Added handle for files with no types , because if no type , it will give IndexError
> Handle-resource-downloader-missing-file-type

- cloudify_common_sdk/filters.py
- cloudify_common_sdk/tests/test_filters.py
- cloudify_rest_sdk/utility.py
Do not restrict the obfuscation to auth.passwords or events/logs - let's
do it pretty much everywhere.
> CY-2754 Obfuscate passwords everywhere

- cloudify_common_sdk/filters.py
- cloudify_rest_sdk/utility.py
- setup.py
A regular expression is used to replace occurances of something like
"password: $3CR3T" with with "password: xxxxxxxxxxxxxxxx" in obfuscated
strings.
> CY-2754 Obfuscate passwords in strings

- CHANGELOG.txt
- cloudify_common_sdk/resource_downloader.py
- cloudify_terminal_sdk/terminal_connection.py
- cloudify_terminal_sdk/tests/test_terminal_connection.py
- setup.py
small fix to encode and decode data as it is sent or received
> RD-278-Fix-Terminal-Encoding

- CHANGELOG.txt
- cloudify_common_sdk/tests/test_cli_tool_base.py
- cloudify_common_sdk/tests/test_utils.py
- cloudify_common_sdk/utils.py
- setup.py
this PR adds support for our intrinsic functions to be resolved if passed through kwargs
> Add-Get-Sys-Support

- CHANGELOG.txt
- cloudify_common_sdk/filters.py
- cloudify_common_sdk/tests/test_filters.py
- setup.py
handling of the regex of numbers before was not considering only numbers , and we added a special case of array of numbers
> CYBL-1593-Better-Handle-Array-Numbers

- CHANGELOG.txt
- cloudify_common_sdk/filters.py
- cloudify_common_sdk/tests/test_filters.py
- setup.py
yet another special case needs handling
> Another-Obfuscate-issue

- CHANGELOG.txt
- cloudify_common_sdk/filters.py
- cloudify_common_sdk/tests/test_filters.py
- setup.py
some more handling for new lines inside string
> re-new-lines

- CHANGELOG.txt
- cloudify_common_sdk/resource_downloader.py
- cloudify_common_sdk/tests/test_resource_downloader.py
- setup.py
Fixing handling git@ -> host not verified and add handling terraform source :: https://www.terraform.io/language/modules/sources
> Add handling git@ and terraform :: resources

- CHANGELOG.txt
- cloudify_common_sdk/processes.py
- setup.py
use the obfuscated value when logging only
> obfuscate-logs-only

- CHANGELOG.txt
- cloudify_common_sdk/tests/test_utils.py
- cloudify_common_sdk/utils.py
- setup.py
allow parsing for get_attribute path , incase the property type is a dict or list
> CYBL-1765-Handle-Complex-Get-Attribute

- CHANGELOG.txt
- cloudify_common_sdk/utils.py
- setup.py
casting the returned value from resolved intrinsic function , causing inconstancy on expected result 
so if you do for example  
```
{ get_attribute : [ node,attribute,value] }
```
where you expect value to be a list , the result would be a string of that list
> RD-5615-Better-Handle-Intrinsic-Results

- CHANGELOG.txt
- cloudify_common_sdk/secure_property_management.py
- setup.py
return the correct resolved value
> Fix-Secure-Property

- CHANGELOG.txt
- cloudify_common_sdk/processes.py
- cloudify_common_sdk/utils.py
- setup.py
add complex path handling to get_secret
> RD-5975-Support-Complex-Get-Secret

- .circleci/config.yml
This will add Jenkins upload to pypi job [ to automate the release end to end ]
> automate-pypi-release

- nativeedge_common_sdk/secure_logging.py
- nativeedge_common_sdk/tests/test_secure_logging.py
- nativeedge_kubernetes_sdk/connection/decorators.py
> [DSPE-4685]

- .circleci/config.yml
- .github/workflows/merge-to-main.yaml
- .github/workflows/unittests.yaml
> [NE01D-261]
